<a href="https://colab.research.google.com/github/malavikavenu99/BuildX-Analytics-Project-MalavikaVenu/blob/main/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import pandas library
import pandas as pd
# Load the dataset
df = pd.read_csv("student.csv")
# Display the first five rows
df.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [2]:
# Check dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    object
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object
 6   hsc_s           215 non-null    object
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object
 9   workex          215 non-null    object
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [3]:
# Check missing values
df.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [4]:
# Missing salary values replaced with 0 because students who were not placed do not have salary records.
df["salary"] = df["salary"].fillna(0)

In [5]:
# Checked and removed duplicate records to improve data quality.
df.duplicated().sum()

np.int64(0)

In [6]:
# Clean text columns
text_columns = ["gender","ssc_b","hsc_b","hsc_s","degree_t","workex","specialisation","status"]
for col in text_columns:
    df[col] = df[col].str.strip().str.title()

In [7]:
df.dtypes

sl_no               int64
gender             object
ssc_p             float64
ssc_b              object
hsc_p             float64
hsc_b              object
hsc_s              object
degree_p          float64
degree_t           object
workex             object
etest_p           float64
specialisation     object
mba_p             float64
status             object
salary            float64
dtype: object

In [8]:
df["salary"] = df["salary"].astype(int)

In [9]:
# Rename columns for consistency
df.rename(columns={
    "ssc_p":"ssc_percentage",
    "hsc_p":"hsc_percentage",
    "degree_p":"degree_percentage",
    "mba_p":"mba_percentage",
    "etest_p":"employability_test_percentage"
}, inplace=True)

In [10]:
# Create performance category column
df["performance_category"] = df["degree_percentage"].apply(
    lambda x: "Excellent" if x >= 75 else
              "Good" if x >= 60 else
              "Average"
)

In [11]:
df.to_csv("cleaned_dataset.csv", index=False)

In [12]:
# Export cleaned dataset
from google.colab import files
files.download("cleaned_dataset.csv")